services:
  nvr_proxy:
    image: nginx:alpine
    container_name: nvr_proxy
    restart: unless-stopped
    ports:
      - '48902:80'
    volumes:
      - /home/nexus/nginx/conf.d:/etc/nginx/conf.d:ro
